name: stl_agent_app
description: STL Agent Betting Management App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  image_picker: ^1.0.4
  image: ^4.1.3
  http: ^1.1.0
  intl: ^0.18.1
  url_launcher: ^6.2.1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/
